name: CI/CD Pipeline Completo com GCP

on:
  push:
    branches: ["main"]

jobs:
  build-push-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push da imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/emulador-de-erros:latest

      - name: Deploy no Servidor GCP
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Puxa a imagem mais recente do Docker Hub
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/emulador-de-erros:latest # <-- MUDE AQUI

            # Para e remove o container antigo para evitar conflitos
            sudo docker stop emulador-de-erros-container || true
            sudo docker rm emulador-de-erros-container || true 

            # Roda o novo container com a imagem atualizada
            sudo docker run -d --name emulador-de-erros-container -p 80:8080 "${{ secrets.DOCKERHUB_USERNAME }}/emulador-de-erros:latest"
