# Nome do workflow que aparecerá na aba "Actions" do GitHub
name: CI/CD Pipeline de Deploy para GCP

# Gatilho: este workflow roda sempre que houver um push no branch 'main'
on:
  push:
    branches: ["main"] # Se seu branch principal for "master", mude aqui

jobs:
  build-push-and-deploy:
    # A máquina virtual que será usada para executar o job
    runs-on: ubuntu-latest

    # Passos que serão executados sequencialmente
    steps:
      # 1. Faz o checkout do seu código do repositório para a máquina virtual
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Faz login no Docker Hub usando os segredos
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Monta a imagem Docker e envia para o Docker Hub
      #    Ele usará seu Makefile e Dockerfile automaticamente.
      - name: Build e Push da imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/emulador-de-erros:latest
